name = "alegria-api"
main = "src/index.ts"
compatibility_date = "2024-10-09"
account_id = "6045b0c922c5f02ca8efe49010a2e687"

# Routes for custom domain
routes = [
  { pattern = "poshta.cloud/api/*", zone_name = "poshta.cloud" },
]

# Workers.dev subdomain (остается включенным для резервного доступа)
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "alegria-cache"
database_id = "3944ed10-6044-4bee-8ed6-e016585ce124"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "alegria-media"

[[kv_namespaces]]
binding = "CACHE"
id = "632b1a9884a849b69b30a3fa59a14996"
preview_id = "632b1a9884a849b69b30a3fa59a14996"

[dev]
port = 8787
local_protocol = "http"

# Environment variables
[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://*.pages.dev,https://*.vercel.app,https://poshta.cloud,https://www.poshta.cloud,http://localhost:3000"
CMS_URL = "https://payload-cms-2.vercel.app"
FRONTEND_URL = "https://poshta.cloud"
WORKERS_DOMAIN = "alegria-api.majakojh.workers.dev"
CLOUDFLARE_ZONE_ID = "1853e9c16cb887cc9f037931443b4b36"
VERCEL_BYPASS_TOKEN = "eTDpdWLCGaI7kjzZTB4L6yE7KztvOXd3"
WEBHOOK_SECRET = "zLcKtwlMEJOHZmVXKJjNZk2GXZ2vrsM-TnoRRFkyF2w"

# Secrets (set via: wrangler secret put CLOUDFLARE_API_TOKEN)
# CLOUDFLARE_API_TOKEN = "..." (DO NOT commit!)
