name = "alegria-api"
main = "src/index.ts"
compatibility_date = "2024-10-09"
account_id = "6045b0c922c5f02ca8efe49010a2e687"

# Routes for custom domain
# API on subdomain: api.poshta.cloud instead of poshta.cloud/api/*
# This avoids conflicts with Pages routing
routes = [
  { pattern = "api.poshta.cloud/*", zone_name = "poshta.cloud" },
]

# Workers.dev subdomain (остается включенным для резервного доступа)
workers_dev = true

# D1 REMOVED: Workers does NOT use D1 for cache (uses KV instead)
# D1 (NEXT_TAG_CACHE_D1) is used only by Frontend for ISR tag cache
# This aligns with original Next.js + Cloudflare Pages architecture

# ============================================
# R2 BINDINGS: CMS Media Storage
# ============================================
# Workers: CMS media access only (alegria-media)
# Pages: ISR incremental cache (nextjs-incremental-cache) - SEPARATE bucket
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "alegria-media"

[[kv_namespaces]]
binding = "CACHE"
id = "632b1a9884a849b69b30a3fa59a14996"
preview_id = "632b1a9884a849b69b30a3fa59a14996"

[dev]
port = 8787
local_protocol = "http"

# Environment variables
[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://*.pages.dev,https://*.vercel.app,https://poshta.cloud,https://www.poshta.cloud,http://localhost:3000"
CMS_URL = "https://payload-cms-2.vercel.app"
FRONTEND_URL = "https://poshta.cloud"
WORKERS_DOMAIN = "alegria-api.majakojh.workers.dev"
CLOUDFLARE_ZONE_ID = "1853e9c16cb887cc9f037931443b4b36"
VERCEL_BYPASS_TOKEN = "eTDpdWLCGaI7kjzZTB4L6yE7KztvOXd3"
WEBHOOK_SECRET = "zLcKtwlMEJOHZmVXKJjNZk2GXZ2vrsM-TnoRRFkyF2w"

# Secrets (set via: wrangler secret put CLOUDFLARE_API_TOKEN)
# CLOUDFLARE_API_TOKEN = "..." (DO NOT commit!)
